### PR TITLE
H2 compatibility

### PR DESCRIPTION
**Pull request by M-Razavi**
add compatibility with H2

### CODE REVIEW

**Comment by hsluoyz** [comment]
Hi @M-Razavi , I'd like to support H2, but introducing more dependencies on this single repo is not a good idea, because anyone using it will have to import dependencies he doesn't use actually. What about creating a new GitHub repository named like ``h2-adapter`` (if hosted here) or ``jcasbin-h2-adapter`` (if hosted under your account or organization)? Then you could extend ``JDBCAdapter`` class in the new repo and override what you want like importing the H2 in ``pom.xml``.

**Comment by M-Razavi** [comment]
Hi, @hsluoyz Thanks for the suggestion. I appreciate.
The Embedded and independent of DBMS instance was the main reason that I added H2 and used instead of Mysql in unit tests. 
I realize the problem of huge dependency on this small repo so I think using H2(or any embedded database) instead of MySql could be a better approach.

**Comment by hsluoyz** [comment]
@M-Razavi So will you create the ``h2-adapter`` repo?

BTW, I think I can merge the version of this PR without ``h2`` dependency, meaning you cannot have ``h2``'s test in this repo, but it supports naturally. This is another simpler option as you don't need to create a new repository for it.

**Comment by M-Razavi** [comment]
I've created  https://github.com/M-Razavi/jdbc-adapter

**Comment by hsluoyz** [comment]
@M-Razavi , I'm afraid you only forked it and added your commits there. You still use JDBCAdapter's package name and class name. and that repo cannot be uploaded to Maven, so no users can actually use it.

**Comment by NicolasFruyAdeo** [comment]
Hi, I just want to point out that this was actually fixed as part of https://github.com/jcasbin/jdbc-adapter/commit/07f86019ef4cfca7e0feb4323027e1d708a174c3 (the String `?rewriteBatchedStatements=true&autoReconnect=true` that was making it incompatible got removed as part of that commit, I suppose it's now up to the user to decide about this kind of configuration)

Therefore, Casbin is perfectly usable with H2 too since v1.1.4.

**Comment by hsluoyz** [comment]
@NicolasFruyAdeo good to know about it! Closed now.

**Pull request closed without merging**
