### PR TITLE
limit batch size

### PR DESCRIPTION
**Pull request by nodece**

### CODE REVIEW

**Comment by hsluoyz** [comment]
@bpatters

**Comment by nodece** [comment]
@hsluoyz Could you release a new version?

**Comment by hsluoyz** [comment]
v1.1.4 has already been released in Maven.

**Comment by nodece** [comment]
Should follow SemVer.

**Comment by hsluoyz** [comment]
You mean v1.2.0? OK. Will do next time.

**Comment by nodece** [comment]
Has breaking change. bump to v2.0.0.

**Comment by hsluoyz** [comment]
@nodece please commit to bump version. I will release it on Maven when you're done.

**Pull request merged**
