### PR TITLE
Optimize to load policy by reducing the number of database connections.

### PR DESCRIPTION
**Pull request by shy1st**
Fix:  https://github.com/jcasbin/jdbc-adapter/issues/22

### CODE REVIEW

**Comment by hsluoyz** [comment]
@shy1st plz fix CI.

**Comment by shy1st** [comment]
@hsluoyz The travis CI build failed beause some test file use the configuration of database connection to connect the database to test.For examole:
捕获
So the report of the travis CI will appear Exception.For example:
捕获1
The other Exception is similar to this.

**Comment by hsluoyz** [comment]
@shy1st Travis CI supports DB well, that's why our previous runs suceeded: https://travis-ci.org/github/jcasbin/jdbc-adapter/builds

image

So it seems that this PR broke the CI.

**Comment by hsluoyz** [comment]
@@arafat-java please review and try the code.

**Pull request merged**
