### PR TITLE
Added id field to jdbc-adapter. Fixed an error.

### PR DESCRIPTION
**Pull request by tldyl**
Fix: [#31](https://github.com/node-casbin/sequelize-adapter/issues/31)

### CODE REVIEW

**Comment by hsluoyz** [comment]
@tldyl please remove Oracle code in this PR. Also merge commits.

image

**Comment by nodece** [comment]
@tldyl I think `id` should be incremental, and set to primary key.

**Comment by hsluoyz** [comment]
@tldyl can you change it based on nodece's comment?

**Comment by hsluoyz** [comment]
@nodece @alikhan866 please review.

**Review by nodece — APPROVED** [review]
LGTM

**Comment by hsluoyz** [comment]
@tldyl please release a new version of this adapter to Maven.

**Comment by nodece** [comment]
@tldyl this is breaking changes. please bump to v3, and update README.md.

**Comment by tldyl** [comment]
I have never released a new version to maven central before. I try to execute `mvn clean deploy -DskipTests=true` directly and return error code 401.

**Comment by hsluoyz** [comment]
@tldyl let me know what you need, I will help you (add your key to Maven dashboard, grant permissions, etc.)

**Comment by tldyl** [comment]
I want to publish the 3.0 version of jdbc-adapter to maven central, but the author of jdbc-adapter is not me. By default, I have no permission to publish new versions.

**Comment by hsluoyz** [comment]
@tldyl how can I add you as another author? I think Maven Central must have some mechanisms to allow multiple maintainers?

**Comment by tldyl** [comment]
Maybe we need to inform the author to release the new version.

**Comment by hsluoyz** [comment]
The author is me. Actually I'm kind of tired of/don't have time for releasing a lot of Java packages by myself manually. I'm not a Java expert, but isn't there any way to automatically release Java packages to Maven or allow other people to release packages?

**Pull request merged**
