### PR TITLE
fix: if MySQL, check the existence of the table.

### PR DESCRIPTION
**Pull request by Javakky-pxv**
I'm using this tool in my product.
However, the CREATE statement cannot be executed due to the restricted user rights of the DB.
Therefore, if I'm using MySQL, this tool needs to check the existence of the table first.

In this PR, if productName is "MySQL", the SHOW TABLE statement will check for the existence of the table.
If the table exists, no further migration will be performed.

### CODE REVIEW

**Comment by hsluoyz** [comment]
@seriouszyx please review

**Comment by seriouszyx** [comment]
@Javakky-pxv Please modify the commit message with conventions such as [Angular](https://www.conventionalcommits.org/en/v1.0.0/#examples).

**Comment by hsluoyz** [comment]
@Javakky-pxv plz fix:

image

**Comment by Javakky-pxv** [comment]
Sorry.
I am not sure about the use properly of "fix" and "refactor".
I don't think this PR is about fixing a bug, but can I use the prefix "fix"?

**Pull request merged**
