### PR TITLE
support oracle

### PR DESCRIPTION
**Pull request by Fengxq2014**
#8

### CODE REVIEW

**Comment by hsluoyz** [comment]
Hi @Fengxq2014 , please fix the Travis CI error: https://travis-ci.org/jcasbin/jdbc-adapter/builds/574792729?utm_source=github_status&utm_medium=notification

**Comment by Fengxq2014** [comment]
there is some err in travis-ci shell

**Comment by hsluoyz** [comment]
seems not fixed?

**Comment by Fengxq2014** [comment]
https://travis-ci.org/jcasbin/jdbc-adapter/jobs/574834040  there is some errors in Travis shell

**Comment by hsluoyz** [comment]
Merged.

**Pull request merged**
