### PR TITLE
feat: improve policy comma handling

### PR DESCRIPTION
**Pull request by m-ignatov**
Fix: https://github.com/casbin/jcasbin/issues/413

### CODE REVIEW

**Comment by hsluoyz** [comment]
@m-ignatov plz fix all errors:

image

**Comment by m-ignatov** [comment]
@hsluoyz Moving `escapeCasbinRule()` & `escapeSingleRule()` to `org.casbin.jcasbin.util.Util` will clear the errors in the Codebeat scan I guess, but let me know if this change is okay and will proceed.

**Comment by hsluoyz** [comment]
@m-ignatov 

1. Run all tests in your localhost beforehand, don't test it here
2. sign CLA

**Comment by m-ignatov** [comment]
@hsluoyz 
1. Tested and the build seems to pass
2. I have agreed already, not sure why it does not update here:
image

**Comment by m-ignatov** [comment]
@hsluoyz it seems the master pipeline has failed deploying the 2.8.0 version to Maven. Could you check?

**Pull request merged**
